# Generated by Django 5.1.7 on 2025-05-22 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_alter_artikel_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'verbose_name_plural': '2. Artikel'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': '1. Kategori'},
        ),
    ]
